# docker-compose.yml
version: "3"
services:
  crud:
    build: .
    depends_on:
      - postgres
    ports:
      - "4000:4000"

  postgres:
    image: postgres:11.2-alpine
    ports: 
      - "5432:5432"   